ECommerce/Controllers/SubcategoriaProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace ECommerce.Controllers
{
    public class SubcategoriaProductoController : Controller
    {
        // GET: SubcategoriaProductos
        public ActionResult Index(Application.Cat_TiendaPromo Acat_TiendaPromo, Application.Cat_Subcategoria Acat_SubCategoriaProducto,
            Application.Cat_Clasificacion Acat_Clasificacion)
        {
            int Id = Convert.ToInt32(Application.Cifrado.Desencriptar(Request.QueryString["Id"]));
            Models.Cat_Subcategoria cat_Subcategoria = new Models.Cat_Subcategoria();
            cat_Subcategoria.Id = Id;

            ViewBag.Promos = Acat_TiendaPromo.Cat_TiendaPromo_Listar(3);

            ViewBag.SubCategorias = Acat_SubCategoriaProducto.Cat_Subcategoria_PorId(cat_Subcategoria);

            ViewBag.Clasificacion = Acat_Clasificacion.Cat_Clasificacion_ListarAleatorio();


            return View();
        }

        [HttpPost]
        public JsonResult Subcategoria_Seleccionar_IdCategoria(Models.CatCategoriaProducto catCategoriaProducto, Application.CatSubcategoria APcatSubcategoria)
        {
            List<Models.CatSubcategoria> dbCatSubcategorias = APcatSubcategoria.CatSubcategoria_Seleccionar_IdCategoria(catCategoriaProducto);
            return Json(dbCatSubcategorias);
        }

        [HttpPost]
        public JsonResult Subcategoria_Agregar(Models.CatSubcategoria catSubcategoria, Application.CatSubcategoria APcatSubcategoria)
        {
            List<Models.ArticuloImg> LstArticuloImg = new List<Models.ArticuloImg>();

            if (Session["ImageneSubCategoria"] != null)
            {
                LstArticuloImg = (List<Models.ArticuloImg>)Session["ImageneSubCategoria"];
            }

            catSubcategoria.Imagen = LstArticuloImg[0].ImagenURL;
            Models.CatSubcategoria cat_Categoria = APcatSubcategoria.CatSubcategoria_Agregar(catSubcategoria);

            if (cat_Categoria.Id > 0)
            {
                Session["ImageneSubCategoria"] = null;
            }

            return Json(cat_Categoria);
        }

        [HttpPost]
        public JsonResult CargaImagenes(List<Models.ArticuloImg> ListaImagenes)
        {
            List<Models.ArticuloImg> LstArticuloImg = new List<Models.ArticuloImg>();
            Session["ImageneSubCategoria"] = null;

            foreach (var dt in ListaImagenes)
            {
                LstArticuloImg.Add(dt);
            }

            Session["ImageneSubCategoria"] = LstArticuloImg;
            return Json(LstArticuloImg);
        }

        [HttpPost]
        public JsonResult ConsulltaImagenes()
        {
            List<Models.ArticuloImg> LstArticuloImg = new List<Models.ArticuloImg>();

            if (Session["ImageneSubCategoria"] != null)
            {
                LstArticuloImg = (List<Models.ArticuloImg>)Session["ImageneSubCategoria"];
            }
            return Json(LstArticuloImg);
        }
    }
}

ECommerce/Controllers/URLSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class URLSController : Controller
    {
        [HttpPost]

        public JsonResult URL_Cifrar(Models.URL uRL)
        {
            Models.URL NewUrl = new Models.URL();
            NewUrl.Url = Application.UrlCifrardo.Encrypt(uRL.UrlVaible);
            return Json(NewUrl);
        }


        //SECURE
        public JsonResult URL_Cifrado(Models.URL uRL)
        {
            Models.URL NewUrl = new Models.URL();
            NewUrl.Url = Application.Cifrado.Encriptar(uRL.UrlVaible);
            return Json(NewUrl);
        }
    }
}

ECommerce/Views/SubcategoriaProducto/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="assets/css/templatemo.css">
<style>
    .ov-btn-grow-skew {
        background: #fff; /* color de fondo */
        color: black !important; /* color de fuente */
        border: 2px solid var(--c-principal); /* tamaño y color de borde */
        padding: 6px 20px;
        border-radius: 3px; /* redondear bordes */
        position: relative;
        z-index: 1;
        overflow: hidden;
        display: inline-block;
    }

        .ov-btn-grow-skew:hover {
            color: whitesmoke !important; /* color de fuente hover */
        }

        .ov-btn-grow-skew::after {
            content: "";
            background: var(--c-principal); /* color de fondo hover */
            position: absolute;
            z-index: -1;
            padding: 16px 20px;
            display: block;
            left: -20%;
            right: -20%;
            top: 0;
            bottom: 0;
            transform: skewX(-45deg) scale(0, 1);
            transition: all 0.3s ease;
        }

        .ov-btn-grow-skew:hover::after {
            transition: all 0.3s ease-out;
            transform: skewX(-45deg) scale(1, 1);
        }
    .puntuacion {
        border-radius: 4px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        transition: box-shadow 0.3s ease-in-out;
    }

        .puntuacion:hover {
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }
    /*Tarjetas*/
    .custom-card {
        background-color: #f8f9fa; /* Color de fondo diferente */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombreado */
    }

    .zoom-effect {
        transition: transform 0.2s ease;
    }

    .zoom-effect:hover {
        transform: scale(1.05);
    }

    /*Mediaquery CARRUCEL*/
    @@media (max-width: 991px) {
        .estetic {
            display: none;
        }

        .img-fluid {
            width: 280px;
        }

        .h1 {
            font-family: 'Roboto', sans-serif;
            font-size: 20px !important;
            font-weight: 200 !important;
        }

        .h2 {
            font-family: 'Roboto', sans-serif;
            font-size: 15px !important;
            font-weight: 300;
        }

        p {
            font-family: 'Roboto', sans-serif;
            font-size: 13px !important;
            font-weight: 300 !important;
        }

        #template-mo-zay-hero-carousel .carousel-indicators li {
            margin-top: -1px;
            background-color: #59ab6e;
        }

        .align-self-center {
            -ms-flex-item-align: center !important;
            align-self: center !important;
            text-align: start;
        }
        /*Mediaquery imgen stars*/
        .imagen {
            height: 131px !important;
        }

        .ulimg {
            font-size: 11px !important;
        }
    }

    @@media (max-width: 720px) {
        #template-mo-zay-hero-carousel {
            background-size: auto;
        }
    }
</style>
<p class="estetic">
    <br />
    <br />
    <br />
</p>
@*CARRUCEL*@
<div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
        @for (var i = 0; i < ViewBag.Promos.Count; i++)
        {
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
        }
    </ol>

    <div class="carousel-inner">
        @foreach (var item in ViewBag.Promos)
        {
            <div class="carousel-item @(item == ViewBag.Promos[0] ? "active" : "")">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid smaller-image mx-auto d-block" src="@item.URLImg" alt="" style="width: 30%">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left align-self-center">
                                <h1 style="color: var(--c-principal); text-shadow: 0 0 1px black, 0 0 1px black, 0 0 1px black, 0 0 1px black;" class="h1"><b>@item.Titulo</b></h1>
                                <h3 style="color: white; text-shadow: 0 0 1px black, 0 0 1px black, 0 0 1px black, 0 0 1px black; " class="h2">@item.Subtitulo</h3>
                                <p style=" color: white; text-shadow: 0 0 1px black, 0 0 1px black, 0 0 1px black, 0 0 1px black;">
                                    <b>@item.Descripcion</b>
                                    <a rel="sponsored" class="text-success" href="@item.Link" target="_blank">Comprar</a> ahora.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>

    <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="prev">
        <i class="fa fa-angle-left f-60"></i>
    </a>

    <a class="carousel-control-next text-decoration-none w-auto pe-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="next">
        <i class="fa fa-angle-right"></i>
    </a>
</div>


@*SUBCATEGORIAS*@
<section class="container py-5">
    <div class="row text-center pt-3">
        <div class="col-lg-6 m-auto">
            <h1 class="h1">Productos por SubCategoria</h1>
            <p>
                Selecciona una subcategoria para ver los productos disponibles en la tienda.
            </p>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-4 g-4">
        @*http://*@

        @foreach (var item in ViewBag.SubCategorias)
        {
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 p-5 mt-3">
                <div class="card custom-card" style="width: 18rem;">
                    <img src="@item.Imagen" class="card-img-top zoom-effect" style="object-fit: cover; height: 234px;" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@item.Nombre</h5>
                        <p class="card-text">Resumen general de la categoria, mencion de algunas marcas o posubles promociones, incremento del texto.</p>
                        <div class="d-flex justify-content-center">
                            <a style="color: white; cursor: pointer;" onclick="Redireccionar(@item.Id)" class="ov-btn-grow-skew">Visualizar</a>
                        </div>
                    </div>
                </div>
            </div>

        }

    </div>
</section>

<!-- Start Featured Product -->
<section class="bg-light">
    <div class="container py-5">
        <div class="row text-center py-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">
                    Productos destacados
                </h1>
                <p>
                    ¡Descubre nuestra selección exclusiva de productos destacados! Te presentamos los artículos más populares y solicitados por nuestros clientes.
                </p>
            </div>
        </div>
        <div class="row">
            @{
                if (ViewBag.Clasificacion != null)
                {
                    foreach (var item in ViewBag.Clasificacion)
                    {
                        <div class="col col-xs-4 col-md-4 mb-4">
                            <div class="card h-100 puntuacion">
                                <a href="#">
                                    <img src="@item.Imagen" class="card-img-top img-fluid imagen" style="height: 400px; object-fit: contain !important;">
                                </a>
                                <div class="card-body" style="background-color: #f8f9fa; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                                    <ul class="list-unstyled d-flex justify-content-between ulimg">
                                        <li>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                            @*<i class="text-muted fa fa-star"></i>*@
                                        </li>
                                        <li class="text-muted text-right">$2240.00</li>
                                    </ul>
                                    <a href="#" class="h2 text-decoration-none text-dark">@item.Nombre</a>
                                    <p class="card-text">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt in culpa qui officia deserunt.
                                    </p>
                                    <p class="text-muted">Reviews (24)</p>
                                </div>
                            </div>
                        </div>
                    }
                }
            }

        </div>
    </div>
</section>
<!-- End Featured Product -->
<script src="assets/js/bootstrap.bundle.min.js"></script>
<script src="assets/js/templatemo.js"></script>


<script>
    function Redireccionar(documento) {
        var obj = {};

        obj['UrlVaible'] = documento;

        var jsonObject = {
            "URL": obj
        };

        $.ajax({
            type: "POST",
            url: "@Url.Action("URL_Cifrado", "URLS")",
            async: false,
            data: JSON.stringify(jsonObject),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
            window.location.href = '@Url.Action("Index", "ClasificacionProducto")?Id=' + result.Url;
            },
            error: function () {
            AlertDanger("Problemas al consultar ", "Intentolo mas tarde.");
            }
        });

    }
</script>